# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - aishawebapi

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Setup Dot Net Version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: build
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.title.startsWith('RELEASES:') &&
      contains(github.event.pull_request.labels.*.name, 'RELEASES')
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04B3EDB6EEE14CA5BAE6C01E7E2D7956 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5874A2640F03413EAA75E2113090578C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21288C2D6088433D9A2EA402503A9920 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aishawebapi'
          slot-name: 'Production'
          package: . 
