name: Build and deploy ASP.Net Core app to Azure Web App - aiaisha

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - master
  workflow_dispatch:
  # Trigger deployment when the title and label are "RELEASES"
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: SET UP .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: BUILD
        run: dotnet build --configuration Release

      - name: TEST
        run: dotnet test --no-build --verbosity normal

      - name: PUBLISH
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: UPLOAD artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    # Only run deployment job when triggered by the release event with specified title and label
    if: github.event_name == 'release' && github.event.release.title == 'RELEASES' && contains(github.event.release.labels.*.name, 'RELEASES')
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aiaisha'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F5B31649074447449F14D14DC796D850 }}
          package: .
